---
default:
  interruptible: true

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

include:
  - component: gitlab.dx1.lseg.com/app/app-51172/ci/components/auto-vault@release/1.x.x-stable
    inputs:
      enable-cd-user-token: false
  - component: gitlab.dx1.lseg.com/app/app-51172/ci/components/versioning@release/1.x.x-stable
  - component: gitlab.dx1.lseg.com/app/app-51172/ci/components/auto-blackduck@d5f81c837001f5bd29dffee4f44746d190ce9826
    inputs:
      always-scan: true
      detect-tools: "DETECTOR, SIGNATURE_SCAN"


stages:
  - .pre
  #- secure-pipeline
  - scan
  - license-scan

variables:
  GIT_DEPTH: 0
  RUNNER_TAG: "acadia_ore_amd64"






