
/*
 Copyright (C) 2006, 2007 Eric Ehlers

 This file is part of QuantLib, a free-software/open-source library
 for financial quantitative analysts and developers - http://quantlib.org/

 QuantLib is free software: you can redistribute it and/or modify it
 under the terms of the QuantLib license.  You should have received a
 copy of the license along with this program; if not, please email
 <quantlib-dev@lists.sf.net>. The license is also available online at
 <http://quantlib.org/license.shtml>.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the license for more details.
*/

// Manual override of the qlCalendarAdvance loop typedefs from loop_calendar.hpp.
// Required because Calendar::advance gained an optional 5th parameter in the
// ORE fork of QuantLib, which gensrc cannot express.  The autogenerated
// loop_calendar.hpp uses cmf4; this file provides the correct cmf5 versions.
// Included by manual.cpp instead of loop_calendar.hpp for qlCalendarAdvance.

#ifndef qlo_loop_calendar_manual_hpp
#define qlo_loop_calendar_manual_hpp

#include <boost/bind.hpp>

namespace QuantLibAddin {

    // qlCalendarAdvance - manual override (cmf5, extra optional parameter)
    // Uses distinct names to avoid conflict with the autogenerated cmf4 typedefs
    // in loop_calendar.hpp.

    typedef     boost::_bi::bind_t<
                QuantLib::Date,
                boost::_mfi::cmf5<
                    QuantLib::Date,
                    QuantLib::Calendar,
                    const QuantLib::Date&,
                    const QuantLib::Period&,
                    QuantLib::BusinessDayConvention,
                    bool,
                    const QuantLib::ext::optional<QuantLib::BusinessDayConvention>&>,
                boost::_bi::list6<
                    boost::_bi::value<QuantLib::Calendar >,
                    boost::_bi::value<QuantLib::Date>,
                    boost::arg<1>,
                    boost::_bi::value<QuantLib::BusinessDayConvention>,
                    boost::_bi::value<bool>,
                    boost::_bi::value<QuantLib::ext::optional<QuantLib::BusinessDayConvention>> > >
                qlCalendarAdvanceBindManual;

    typedef     QuantLib::Date
                (QuantLib::Calendar::* qlCalendarAdvanceSignatureManual)(
                    const QuantLib::Date&,
                    const QuantLib::Period&,
                    QuantLib::BusinessDayConvention,
                    bool,
                    const QuantLib::ext::optional<QuantLib::BusinessDayConvention>&) const;

}

#endif
